<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ListWorksSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if (DB::table(\App\Core\Config\ListDatabaseTable::TABLE_LIST_WORKS)->count() === 0) {
            DB::table(\App\Core\Config\ListDatabaseTable::TABLE_LIST_WORKS)->insert([

                /* Учебно-методические материалы */
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::MET_WORK,
                    'workCaption' => 'Написание и подготовка к изданию:',
                    'subCaption' => 'учебников',
                    'comment' => 'Из расчета на один печатный лист (40 000 знаков).',
                    'maxHours' => 70,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::MET_WORK,
                    'workCaption' => 'Написание и подготовка к изданию:',
                    'subCaption' => 'учебных пособий',
                    'comment' => 'Из расчета на один печатный лист (40 000 знаков).',
                    'maxHours' => 70,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::MET_WORK,
                    'workCaption' => 'Написание и подготовка к изданию:',
                    'subCaption' => 'конспектов лекций, сборников задач и упражнений, руководств к лабораторным работам и др.',
                    'comment' => 'Из расчета на один печатный лист (40 000 знаков).',
                    'maxHours' => 70,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::MET_WORK,
                    'workCaption' => 'Написание и подготовка к изданию:',
                    'subCaption' => 'методических указаний к практическим занятиям, курсовому и дипломному проектированию, методических указаний по изучению курса с контрольными заданиями, планов семинарских занятий и др-',
                    'comment' => 'Из расчета на один печатный лист (40 000 знаков).',
                    'maxHours' => 70,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::MET_WORK,
                    'workCaption' => 'Переработка:',
                    'subCaption' => 'учебников',
                    'comment' => 'Из расчета на один печатный лист (40 000 знаков).',
                    'maxHours' => 50,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::MET_WORK,
                    'workCaption' => 'Переработка:',
                    'subCaption' => 'учебных пособий',
                    'comment' => 'Из расчета на один печатный лист (40 000 знаков).',
                    'maxHours' => 50,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::MET_WORK,
                    'workCaption' => 'Переработка:',
                    'subCaption' => 'конспектов лекций, сборников задач и упражнений, руководств к лабораторным работам и др.',
                    'comment' => 'Из расчета на один печатный лист (40 000 знаков).',
                    'maxHours' => 30,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::MET_WORK,
                    'workCaption' => 'Переработка:',
                    'subCaption' => 'методических указаний к практическим занятиям, курсовому и дипломному проектированию, методических указаний по изучению курса с контрольными заданиями, планов семинарских занятий и ДР-',
                    'comment' => 'Из расчета на один печатный лист (40 000 знаков).',
                    'maxHours' => 30,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::MET_WORK,
                    'workCaption' => 'Разработка учебного плана для направления (специальности)',
                    'subCaption' => '',
                    'comment' => '',
                    'maxHours' => 40,
                ],[
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::MET_WORK,
                    'workCaption' => 'Переработка учебного плана для направления (специальности)',
                    'subCaption' => '',
                    'comment' => '',
                    'maxHours' => 20,
                ],[
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::MET_WORK,
                    'workCaption' => 'Разработка рабочей программы, программ учебной и производственной практик',
                    'subCaption' => '',
                    'comment' => '',
                    'maxHours' => 20,
                ],[
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::MET_WORK,
                    'workCaption' => 'Переработка рабочей программы, программ учебной и производственной практик',
                    'subCaption' => '',
                    'comment' => '',
                    'maxHours' => 10,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::MET_WORK,
                    'workCaption' => 'Разработка электронных версий учебных и учебно-методических пособий с использованием интерактивных информационных технологий, в том числе для электронного обучения',
                    'subCaption' => '',
                    'comment' => 'Время определяет заведующий кафедрой из расчета 100 часов за 25 страниц электронного текста',
                    'maxHours' => 0,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::MET_WORK,
                    'workCaption' => 'Разработка олимпиадных заданий:',
                    'subCaption' => 'для 9-11 классов',
                    'comment' => '',
                    'maxHours' => 15,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::MET_WORK,
                    'workCaption' => 'Разработка олимпиадных заданий:',
                    'subCaption' => 'для 1-8 классов',
                    'comment' => '',
                    'maxHours' => 10,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::MET_WORK,
                    'workCaption' => 'Проверка, консультирование и прием контрольных, расчетнографических работ, расчетных заданий, рефератов, домашних заданий и других работ',
                    'subCaption' => '',
                    'comment' => 'На одно задание. За исключением рефератов',
                    'maxHours' => 0.25,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::MET_WORK,
                    'workCaption' => 'Разработка и постановка новых лабораторных работ (в том числе компьютерных моделей и т.п.)',
                    'subCaption' => '',
                    'comment' => 'на одну лабораторную работу',
                    'maxHours' => 150,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::MET_WORK,
                    'workCaption' => 'Модернизация действующих лабораторных работ (в том числе компьютерных моделей и т.п.)',
                    'subCaption' => '',
                    'comment' => 'на одну лабораторную работу',
                    'maxHours' => 50,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::MET_WORK,
                    'workCaption' => 'Подготовка к лекционным, семинарским, лабораторным, практическим занятиям',
                    'subCaption' => 'по вводимой и новой для преподавателя дисциплине',
                    'comment' => 'на одно занятие',
                    'maxHours' => 4,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::MET_WORK,
                    'workCaption' => 'Подготовка к лекционным, семинарским, лабораторным, практическим занятиям',
                    'subCaption' => 'по читаемой дисциплине',
                    'comment' => 'на одно занятие',
                    'maxHours' => 0.5,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::MET_WORK,
                    'workCaption' => 'Разработка оценочных материалов:',
                    'subCaption' => 'деловых игр',
                    'comment' => 'на 4-8-часовое занятие',
                    'maxHours' => 10,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::MET_WORK,
                    'workCaption' => 'Разработка оценочных материалов:',
                    'subCaption' => 'тестовых и контрольных заданий по дисциплине',
                    'comment' => 'на одно задание',
                    'maxHours' => 10,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::MET_WORK,
                    'workCaption' => 'Разработка оценочных материалов:',
                    'subCaption' => 'билетов к зачетам и экзаменам',
                    'comment' => 'на учебную дисциплину',
                    'maxHours' => 15,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::MET_WORK,
                    'workCaption' => 'Разработка оценочных материалов:',
                    'subCaption' => 'тесты и программы, контролирующие освоение обучающимися учебной дисциплины',
                    'comment' => 'на учебную дисциплину',
                    'maxHours' => 50,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::MET_WORK,
                    'workCaption' => 'Разработка оценочных материалов:',
                    'subCaption' => 'вопросов к вступительным экзаменам в аспирантуру',
                    'comment' => '',
                    'maxHours' => 15,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::MET_WORK,
                    'workCaption' => 'Разработка оценочных материалов:',
                    'subCaption' => 'вопросов к кандидатскому экзамену',
                    'comment' => '',
                    'maxHours' => 15,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::MET_WORK,
                    'workCaption' => 'Переработка оценочных материалов:',
                    'subCaption' => 'деловых игр',
                    'comment' => 'на 4-8-часовое занятие',
                    'maxHours' => 2,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::MET_WORK,
                    'workCaption' => 'Переработка оценочных материалов:',
                    'subCaption' => 'тестовых и контрольных заданий по дисциплине',
                    'comment' => 'на одно задание',
                    'maxHours' => 2,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::MET_WORK,
                    'workCaption' => 'Переработка оценочных материалов:',
                    'subCaption' => 'билетов к зачетам и экзаменам',
                    'comment' => 'на учебную дисциплину',
                    'maxHours' => 5,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::MET_WORK,
                    'workCaption' => 'Переработка оценочных материалов:',
                    'subCaption' => 'тесты и программы, контролирующие освоение обучающимися учебной дисциплины',
                    'comment' => 'на учебную дисциплину',
                    'maxHours' => 10,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::MET_WORK,
                    'workCaption' => 'Переработка оценочных материалов:',
                    'subCaption' => 'вопросов к вступительным экзаменам в аспирантуру',
                    'comment' => '',
                    'maxHours' => 5,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::MET_WORK,
                    'workCaption' => 'Переработка оценочных материалов:',
                    'subCaption' => 'вопросов к кандидатскому экзамену',
                    'comment' => '',
                    'maxHours' => 5,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::MET_WORK,
                    'workCaption' => 'Разработка расчетнографической работы',
                    'subCaption' => '',
                    'comment' => 'на одну работу',
                    'maxHours' => 100,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::MET_WORK,
                    'workCaption' => 'Модернизация расчетнографической работы',
                    'subCaption' => '',
                    'comment' => 'на одну работу',
                    'maxHours' => 50,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::MET_WORK,
                    'workCaption' => 'Работы, связанные с применением информационных технологий в учебном процессе (разработка задач, отладка программ и т.п.)',
                    'subCaption' => '',
                    'comment' => 'время определяет заведующий кафедрой',
                    'maxHours' => 100,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::MET_WORK,
                    'workCaption' => 'Работа в научно-методических советах, президиумах и советах учебно-методического объединения и других постоянных или временных советах, рабочих группах, создаваемых Минобрнауки России',
                    'subCaption' => '',
                    'comment' => 'по фактически затраченному времени, но не более 24 часов в год',
                    'maxHours' => 24,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::MET_WORK,
                    'workCaption' => 'Работа в редколлегиях научных журналов и т.п. органах',
                    'subCaption' => '',
                    'comment' => 'по фактически затраченному времени, но не более 30 часов в год',
                    'maxHours' => 30,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::MET_WORK,
                    'workCaption' => 'Работа в Учебно-методическом совете и Редакционноиздательском совете',
                    'subCaption' => '',
                    'comment' => 'по фактически затраченному времени, но не более 30 часов в год',
                    'maxHours' => 30,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::MET_WORK,
                    'workCaption' => 'Проведение олимпиад школьников: участие в заседаниях оргкомитетов, работе методических комиссий, жюри',
                    'subCaption' => '',
                    'comment' => 'По фактически затраченному времени, в соответствии с планами работ',
                    'maxHours' => 0,
                ],

                /* Научное-исследовательские работы */
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::SIC_WORK,
                    'workCaption' => 'Подготовка к изданию:',
                    'subCaption' => 'монографии',
                    'comment' => 'на один печатный лист',
                    'maxHours' => 150,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::SIC_WORK,
                    'workCaption' => 'Подготовка к изданию:',
                    'subCaption' => 'научной статьи в индексируемых изданиях Web of Science и Scopus',
                    'comment' => 'на один печатный лист',
                    'maxHours' => 200,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::SIC_WORK,
                    'workCaption' => 'Подготовка к изданию:',
                    'subCaption' => 'научной статьи в журнале из списка ВАК',
                    'comment' => 'на один печатный лист',
                    'maxHours' => 100,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::SIC_WORK,
                    'workCaption' => 'Подготовка к изданию:',
                    'subCaption' => 'научной статьи в индексируемых изданиях РИНЦ',
                    'comment' => 'на один печатный лист',
                    'maxHours' => 50,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::SIC_WORK,
                    'workCaption' => 'Подготовка к изданию:',
                    'subCaption' => 'научной статьи в прочих изданиях',
                    'comment' => 'на один печатный лист',
                    'maxHours' => 30,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::SIC_WORK,
                    'workCaption' => 'Выступление с докладом на научных конференциях, конгрессах, симпозиумах, «круглых столах», чтениях, семинарах, школах',
                    'subCaption' => '',
                    'comment' => 'в год',
                    'maxHours' => 60,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::SIC_WORK,
                    'workCaption' => 'Выполнение плановых инициативных НИР',
                    'subCaption' => '',
                    'comment' => 'по решению НТС (решение прикладывается к отчету); при условии, что преподаватель не получает заработную плату за участие в НИР',
                    'maxHours' => 200,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::SIC_WORK,
                    'workCaption' => 'Подготовка студентов к участию в конференциях:',
                    'subCaption' => 'международных',
                    'comment' => 'на одну работу',
                    'maxHours' => 10,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::SIC_WORK,
                    'workCaption' => 'Подготовка студентов к участию в конференциях:',
                    'subCaption' => 'всероссийских',
                    'comment' => 'на одну работу',
                    'maxHours' => 5,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::SIC_WORK,
                    'workCaption' => 'Подготовка студентов к участию в конференциях:',
                    'subCaption' => 'университетских',
                    'comment' => 'на одну работу',
                    'maxHours' => 3,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::SIC_WORK,
                    'workCaption' => 'Руководство инициативной научно-исследовательской работой студентов',
                    'subCaption' => '',
                    'comment' => 'на одного студента в семестр',
                    'maxHours' => 30,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::SIC_WORK,
                    'workCaption' => 'Подготовка университетской команды для участия в международных, всероссийских или региональных студенческих олимпиадах или конкурсах',
                    'subCaption' => '',
                    'comment' => '',
                    'maxHours' => 100,
                ],

                /* Организационно-методические работы */
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::ORG_WORK,
                    'workCaption' => 'Работа в приемной комиссии (в том числе ответственный секретарь, член отборочной комиссии и т.д.)',
                    'subCaption' => '',
                    'comment' => '',
                    'maxHours' => -1,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::ORG_WORK,
                    'workCaption' => 'Участие в работе Ученого совета Университета (института) и диссертационных советах:',
                    'subCaption' => 'членам совета',
                    'comment' => '',
                    'maxHours' => 40,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::ORG_WORK,
                    'workCaption' => 'Участие в работе Ученого совета Университета (института) и диссертационных советах:',
                    'subCaption' => 'ученым секретарям советов',
                    'comment' => '',
                    'maxHours' => 100,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::ORG_WORK,
                    'workCaption' => 'Участие в заседаниях:',
                    'subCaption' => 'кафедры',
                    'comment' => '',
                    'maxHours' => 25,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::ORG_WORK,
                    'workCaption' => 'Участие в заседаниях:',
                    'subCaption' => 'учебно-методических и научно-технических семинарах',
                    'comment' => '',
                    'maxHours' => 40,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::ORG_WORK,
                    'workCaption' => 'Организационно-методическая работа по заданиям',
                    'subCaption' => 'Минобрнауки России',
                    'comment' => '',
                    'maxHours' => 240,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::ORG_WORK,
                    'workCaption' => 'Организационно-методическая работа по заданиям',
                    'subCaption' => 'ректората',
                    'comment' => '',
                    'maxHours' => 150,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::ORG_WORK,
                    'workCaption' => 'Организационно-методическая работа по заданиям',
                    'subCaption' => 'директоров институтов и заведующих кафедрами',
                    'comment' => '',
                    'maxHours' => 100,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::ORG_WORK,
                    'workCaption' => 'Руководство студенческими курсами (группами)',
                    'subCaption' => '',
                    'comment' => '',
                    'maxHours' => 120,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::ORG_WORK,
                    'workCaption' => 'Участие в работе научно- методических советов и комиссиях при органах по управлению высшей школой',
                    'subCaption' => '',
                    'comment' => '',
                    'maxHours' => 15,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::ORG_WORK,
                    'workCaption' => 'Руководство студенческими школами, кружками, клубами, секциями',
                    'subCaption' => '',
                    'comment' => '',
                    'maxHours' => 100,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::ORG_WORK,
                    'workCaption' => 'Подготовка и проведение «Дня открытых дверей»',
                    'subCaption' => '',
                    'comment' => '',
                    'maxHours' => 18,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::ORG_WORK,
                    'workCaption' => 'Дежурство на кафедре',
                    'subCaption' => '',
                    'comment' => '',
                    'maxHours' => 6,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::ORG_WORK,
                    'workCaption' => 'Участие в проведении университетских (институтских) мероприятиях по учебно- воспитательной работе',
                    'subCaption' => '',
                    'comment' => '',
                    'maxHours' => 3,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::ORG_WORK,
                    'workCaption' => 'Руководство кафедрой',
                    'subCaption' => '',
                    'comment' => '',
                    'maxHours' => 80,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::ORG_WORK,
                    'workCaption' => 'Работа в Научно-техническом совете Университета',
                    'subCaption' => '',
                    'comment' => '',
                    'maxHours' => 30,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::ORG_WORK,
                    'workCaption' => 'Организация воспитательных, культурно-массовых и спортивно- оздоровительных мероприятий, в том числе:',
                    'subCaption' => 'организация и проведение внутривузовских мероприятий и спортивных соревнований',
                    'comment' => '',
                    'maxHours' => 40,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::ORG_WORK,
                    'workCaption' => 'Организация воспитательных, культурно-массовых и спортивно- оздоровительных мероприятий, в том числе:',
                    'subCaption' => 'подготовка команд обучающихся к участию в межвузовских мероприятиях',
                    'comment' => '',
                    'maxHours' => 40,
                ],
                [
                    'idWorkType' => \App\Core\Constants\ListWorkTypeConstants::ORG_WORK,
                    'workCaption' => 'Организация воспитательных, культурно-массовых и спортивно- оздоровительных мероприятий, в том числе:',
                    'subCaption' => 'прочие мероприятия',
                    'comment' => '',
                    'maxHours' => 1,
                ],
            ]);
        }
    }
}
